### ISSUE TITLE
Cannot install elm-format Atom Package

### ISSUE THREAD

**Issue by conradwt** [avh4/elm-format#212]
I have installed elm-format for Atom by doing the following:

```
$ apm install elm-format
```

However, `which elm-format` doesn't generate a Unix path.  Thus, are there additional instructions for getting this installed?  Where should the binary application (i.e. `elm-format`) reside?

**Comment by avh4** [comment]
It should be on your $PATH, which will commonly be `/usr/local/bin/`.  Another recommendation is to put it in the same folder that `elm-make` is in.

https://github.com/avh4/elm-format#installation-

Updates to the elm-format README are welcome if you can help make it more clear.

**Comment by conradwt** [comment]
@avh4 This executable isn't being installed after execution of the command, `apm install elm-format`.  Thus, I'll try one of the pre-built binary distributions.

**Comment by avh4** [comment]
Ah, yes, elm-format has to be installed first.  I've updated the README today to add that step for all editor plugins:  https://github.com/avh4/elm-format#atom-elm-format-installation

**Comment by Rolograaf** [comment]
Sorry I still do not understand. everything worked nicely before 0.17 now I keep getting errors. Tried a lot of things re-installing atom, beautify, elm-format etc.
Error `Could not find 'elm-format'. The program may not be installed.`

**Comment by avh4** [comment]
Ah, okay.  Are you still able to run `elm-format` from your terminal?

**Comment by Rolograaf** [comment]
there is no `apm install atom-elm-format` 
`failed Request for package information failed: Not found`

I'm on Win10, I do not have a `/usr/local/bin` to put elm-format

and there is no executable? What should Beautify find even when it was in my path?

Sorry all instructions are rather confusing.

**Comment by avh4** [comment]
The apm command should be: `apm install elm-format`  (I've corrected the README.)

When you download elm-format from https://github.com/avh4/elm-format/blob/master/README.md#installation-
you should unzip the zip file and have `elm-format.exe`.  I would suggest putting it in whatever folder `elm.exe` and `elm-make.exe` are in on your computer.

**Comment by Rolograaf** [comment]
That makes a lot of sense, sorry I should have figured that out myself.

One more question, it now gives a red `elm-format exited with code 1` when I save an elm file, I think something must be wrong with my atom core packages maybe?

**Comment by avh4** [comment]
I believe that means either that the plugin didn't find elm-format, or that elm-format couldn't parse your file.

Were you able to run elm-format from the terminal?  You mentioned you're on Windows, so you'll probably have to put the full path to elm-format.exe in the settings page for the elm-format atom plugin.

If that looks like it's set correctly, you could try formatting a file containing just the following to check that it's working:

```elm
foo = ()
```

**Comment by simonh1000** [comment]
@avh4  I have a variation on the same issue. In Atom I can do Ctrl+Alt+B and get formatting, but when I save (Ctrl+S) I get an error `elm-format exited with code null`. (I also got a similar error in OSX). I think I have the correct plugins and `which elm-format` is working. What's happening?

![image](https://cloud.githubusercontent.com/assets/5256724/20012365/352b6c6c-a2af-11e6-9f27-f4467735e0f1.png)

**Comment by avh4** [comment]
can you try going to the settings for the elm-format plugin and setting the elm format path to whatever `which elm-format` gives you?

**Comment by simonh1000** [comment]
thanks - seems to have helped

**Comment by Hasimir0** [comment]
I just found out that if I have an error in the code, the elm-format "exits with code 1"

I tried compiling the code without the pretty formatting, and that's when the elm compiler pointed out the specific error.
Once that got fixed, elm-format worked without flaw.

Maybe this is helpful info?

**Comment by hartmut27** [comment]
I confirm explicitly specifing ```elm-format``` package settings in atom editor solves the issue.
(setting: ```binary path``` -> ```path for elm-format```).
```elm-format exited with code null``` error message disappears, 
then ```elm-format exited with code 1``` appears only as long as there are syntax errors, which is perfectly correct.

**Comment by m0nq** [comment]
Sorry. Been following all the advice, and still can't seem to get it installed properly. :/
Every time I try to install it (both in the command line and in atom package manager) then ask 'which elm-format' it doesn't return anything.

**Comment by avh4** [comment]
> *UPDATE: was able to successfully install and use it through npm

**Comment by Aion-github** [comment]
for **windows** people still struggling with this: 
👉 step1: `apm install elm-format`
👉 step2: then make sure you have `Elm Platform` installed from [here](https://github.com/elm-lang/elm-platform).
👉 step3: make sure you unzipped the `elm-format` **executable**[ from here ](https://github.com/avh4/elm-format/releases/tag/0.7.0-exp) - and place it inside the same folder as the **Elm Platform installation** - you can see it in the path below.
👉 step4: include `C:/Program Files (x86)/Elm Platform/0.18/bin/elm-format.exe` path in the box of elm-format package - inside the Atom UI - Settings tab as you can see below.

![atom error elm-format exited with code null - how to fix this error in windows 10](https://cloud.githubusercontent.com/assets/20288140/26254054/f634c298-3cbd-11e7-919e-b76436bde606.png)
